services:
  - type: web
    name: autosales-backend
    rootDir: AutoSales/backend
    env: node
    region: ohio
    plan: free
    branch: Felipe-Andreau
    buildCommand: npm install && npm run build
    startCommand: DATABASE_URL=$DATABASE_URL npx prisma migrate deploy && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRISMA_CLI_QUERY_ENGINE_TYPE
        value: binary
      - key: PRISMA_CLIENT_ENGINE_TYPE
        value: binary
      - key: PRISMA_ENGINE_TYPE
        value: binary
      - key: DATABASE_URL
        value: postgresql://postgres.fbhsysehqmgvlykzqaug:Hayabusa197829091978@aws-1-sa-east-1.pooler.supabase.com:5432/postgres?pgbouncer=true&sslmode=require&connection_limit=1
      - key: DIRECT_DATABASE_URL
        value: postgresql://postgres:Hayabusa197829091978@db.fbhsysehqmgvlykzqaug.supabase.co:5432/postgres?sslmode=require
      - key: JWT_SECRET
        value: AutoSales2024_JWT_SECRET_SUPER_SEGURO_RENDER_DEPLOY
      - key: CORS_ORIGIN
        value: https://autosales-frontend-2z6au7krw-felipeandreaus-projects.vercel.app
      - key: PORT
        value: 10000