services:
  - type: web
    name: autosales-backend
    rootDir: AutoSales/backend
    env: node
    region: ohio
    plan: free
    branch: Felipe-Andreau
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Set manually in Render dashboard
      - key: DIRECT_URL
        sync: false # Set manually in Render dashboard  
      - key: JWT_SECRET
        sync: false # Set manually in Render dashboard
      - key: PORT
        value: 10000